theme: jekyll-theme-hacker
title: "Md. Shihabuddin Sadi"
description: "Software Engineer | DevOps & Cloud Native Engineer | Aspiring Platform Engineer"

github:
  is_project_page: true
  repository_url: "https://github.com/sadishihab"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag  # Added for better SEO metadata (recommended)

# RSS Feed configuration
feed:
  path: feed.xml
  title: "Md. Shihabuddin Sadi Blog"
  description: "DevOps, Cloud, Kubernetes, and Automation"
  url: "https://sadishihab.github.io"

# SEO Meta Description (for better discoverability)
seo_description: "Md. Shihabuddin Sadi — Software Engineer specializing in DevOps, Cloud Native technologies, and Platform Engineering. Experienced in Kubernetes, Docker, CI/CD pipelines, and Infrastructure as Code (IaC). Passionate about automating workflows, optimizing developer experience, and building scalable cloud platforms."
