theme: jekyll-theme-hacker
title: "Md. Shihabuddin Sadi"
description: "Software Engineer | DevOps & Cloud Native Engineer | Aspiring Platform Engineer"

github:
  is_project_page: true
  repository_url: "https://github.com/sadishihab"

# Plugins
plugins:
  - jekyll-feed

# RSS Feed configuration
feed:
  path: feed.xml
  title: "Md. Shihabuddin Sadi Blog"
  description: "DevOps, Cloud, Kubernetes, and Automation"
  # url is optional, GitHub Pages will usually detect it automatically
  url: "https://sadishihab.github.io"
