theme: jekyll-theme-hacker

title: "Md. Shihabuddin Sadi"
description: "Software Engineer specializing in DevOps, Cloud Native technologies, and Platform Engineering. Experienced in Kubernetes, Docker, CI/CD pipelines, and Infrastructure as Code (IaC). Passionate about automating workflows, optimizing developer experience, and building scalable cloud platforms."

author:
  name: "Md. Shihabuddin Sadi"
  url: "https://github.com/sadishihab"
  twitter: "sadishihab"  # optional – if you have a Twitter/X handle

github:
  is_project_page: true
  repository_url: "https://github.com/sadishihab"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag  # for SEO metadata

# RSS Feed configuration
feed:
  path: feed.xml
  title: "Md. Shihabuddin Sadi Blog"
  description: "DevOps, Cloud, Kubernetes, and Automation"
  url: "https://sadishihab.github.io"
