theme: jekyll-theme-hacker

title: "Md. Shihabuddin Sadi"
description: "Software Engineer specializing in DevOps, Cloud Native technologies, and Platform Engineering. Experienced in Kubernetes, Docker, CI/CD pipelines, and Infrastructure as Code (IaC). Passionate about automating workflows, optimizing developer experience, and building scalable cloud platforms."

author:
  name: "Md. Shihabuddin Sadi"
  url: "https://github.com/sadishihab"

github:
  is_project_page: true
  repository_url: "https://github.com/sadishihab"

social:
  name: "Md. Shihabuddin Sadi"
  links:
    - "https://github.com/sadishihab"
    - "https://www.linkedin.com/in/md-shihabuddin-sadi/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag  # for SEO metadata and structured data

# RSS Feed configuration
feed:
  path: feed.xml
  title: "Md. Shihabuddin Sadi Blog"
  description: "DevOps, Cloud, Kubernetes, and Automation"
  url: "https://sadishihab.github.io"
